<?php $view->getLayoutTemplate()->subTitle = 'Bejelentkezés'; ?>
<h1>Bejelentkezés</h1>
<?php if ($showLoginError): ?>
<p class="validationError">Helyetelen felhasználónév vagy jelszó!<p>
<?php endif; ?>
<form action="<?php echo $this->view->generateLink('user', 'login'); ?>" method="post">
  <table>
    <tr>
      <th><label for="userName">Felhasználónév:</label></th>
      <td><input type="text" id="userName" name="userName" value="<?php echo $userName; ?>"/></td>
    </tr>
    <?php echo $this->view->getValidationResultRow($validationErrors, 'userName'); ?>
    <tr>
      <th><label for="password">Jelszó:</label></th>
      <td><input type="password" id="password" name="password"/></td>
    </tr>
    <?php echo $this->view->getValidationResultRow($validationErrors, 'password'); ?>
    <tr class="separator">
      <td>&nbsp;</td>
      <td>
        <input type="submit" name="login" value="Bejelentkezés"/>
        vagy <a href="<?php echo $this->view->generateLink('user', 'register'); ?>">Regisztráció</a>
      </td>
    </tr>
  </table>
</form>